//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: data.cs
// Generation date: 2011/07/02 03:41:46 PM
namespace QAManagementModel
{
    
    /// <summary>
    /// There are no comments for QAManagementEntities in the schema.
    /// </summary>
    public partial class QAManagementEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new QAManagementEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public QAManagementEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Companies
        {
            get
            {
                if ((this._Companies == null))
                {
                    this._Companies = base.CreateQuery<Company>("Companies");
                }
                return this._Companies;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Companies;
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Comment> Comments
        {
            get
            {
                if ((this._Comments == null))
                {
                    this._Comments = base.CreateQuery<Comment>("Comments");
                }
                return this._Comments;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Comment> _Comments;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Project>("Projects");
                }
                return this._Projects;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Project> _Projects;
        /// <summary>
        /// There are no comments for ProjectUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProjectUser> ProjectUsers
        {
            get
            {
                if ((this._ProjectUsers == null))
                {
                    this._ProjectUsers = base.CreateQuery<ProjectUser>("ProjectUsers");
                }
                return this._ProjectUsers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProjectUser> _ProjectUsers;
        /// <summary>
        /// There are no comments for Requirements in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Requirement> Requirements
        {
            get
            {
                if ((this._Requirements == null))
                {
                    this._Requirements = base.CreateQuery<Requirement>("Requirements");
                }
                return this._Requirements;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Requirement> _Requirements;
        /// <summary>
        /// There are no comments for TestResults in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TestResult> TestResults
        {
            get
            {
                if ((this._TestResults == null))
                {
                    this._TestResults = base.CreateQuery<TestResult>("TestResults");
                }
                return this._TestResults;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TestResult> _TestResults;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
        /// <summary>
        /// There are no comments for ProjectUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjectUsers(ProjectUser projectUser)
        {
            base.AddObject("ProjectUsers", projectUser);
        }
        /// <summary>
        /// There are no comments for Requirements in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRequirements(Requirement requirement)
        {
            base.AddObject("Requirements", requirement);
        }
        /// <summary>
        /// There are no comments for TestResults in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTestResults(TestResult testResult)
        {
            base.AddObject("TestResults", testResult);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    }
    /// <summary>
    /// There are no comments for QAManagementModel.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Company
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(long ID)
        {
            Company company = new Company();
            company.ID = ID;
            return company;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ContactPerson in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContactPerson
        {
            get
            {
                return this._ContactPerson;
            }
            set
            {
                this.OnContactPersonChanging(value);
                this._ContactPerson = value;
                this.OnContactPersonChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContactPerson;
        partial void OnContactPersonChanging(string value);
        partial void OnContactPersonChanged();
        /// <summary>
        /// There are no comments for Property ContactPersonNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContactPersonNumber
        {
            get
            {
                return this._ContactPersonNumber;
            }
            set
            {
                this.OnContactPersonNumberChanging(value);
                this._ContactPersonNumber = value;
                this.OnContactPersonNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContactPersonNumber;
        partial void OnContactPersonNumberChanging(string value);
        partial void OnContactPersonNumberChanged();
        /// <summary>
        /// There are no comments for Property ContactEmail in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContactEmail
        {
            get
            {
                return this._ContactEmail;
            }
            set
            {
                this.OnContactEmailChanging(value);
                this._ContactEmail = value;
                this.OnContactEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContactEmail;
        partial void OnContactEmailChanging(string value);
        partial void OnContactEmailChanged();
        /// <summary>
        /// There are no comments for Property Address1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this.OnAddress1Changing(value);
                this._Address1 = value;
                this.OnAddress1Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address1;
        partial void OnAddress1Changing(string value);
        partial void OnAddress1Changed();
        /// <summary>
        /// There are no comments for Property Address2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this.OnAddress2Changing(value);
                this._Address2 = value;
                this.OnAddress2Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address2;
        partial void OnAddress2Changing(string value);
        partial void OnAddress2Changed();
        /// <summary>
        /// There are no comments for Property Address3 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address3
        {
            get
            {
                return this._Address3;
            }
            set
            {
                this.OnAddress3Changing(value);
                this._Address3 = value;
                this.OnAddress3Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address3;
        partial void OnAddress3Changing(string value);
        partial void OnAddress3Changed();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property OfficePhoneNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OfficePhoneNumber
        {
            get
            {
                return this._OfficePhoneNumber;
            }
            set
            {
                this.OnOfficePhoneNumberChanging(value);
                this._OfficePhoneNumber = value;
                this.OnOfficePhoneNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OfficePhoneNumber;
        partial void OnOfficePhoneNumberChanging(string value);
        partial void OnOfficePhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property OfficeEmail in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OfficeEmail
        {
            get
            {
                return this._OfficeEmail;
            }
            set
            {
                this.OnOfficeEmailChanging(value);
                this._OfficeEmail = value;
                this.OnOfficeEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OfficeEmail;
        partial void OnOfficeEmailChanging(string value);
        partial void OnOfficeEmailChanged();
        /// <summary>
        /// There are no comments for Property Validated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Validated
        {
            get
            {
                return this._Validated;
            }
            set
            {
                this.OnValidatedChanging(value);
                this._Validated = value;
                this.OnValidatedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Validated;
        partial void OnValidatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnValidatedChanged();
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Project> Projects
        {
            get
            {
                return this._Projects;
            }
            set
            {
                if ((value != null))
                {
                    this._Projects = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Project> _Projects = new global::System.Collections.ObjectModel.Collection<Project>();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<User> Users
        {
            get
            {
                return this._Users;
            }
            set
            {
                if ((value != null))
                {
                    this._Users = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<User> _Users = new global::System.Collections.ObjectModel.Collection<User>();
    }
    /// <summary>
    /// There are no comments for QAManagementModel.Comment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Comment
    {
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Comment CreateComment(long ID)
        {
            Comment comment = new Comment();
            comment.ID = ID;
            return comment;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Comment1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment1
        {
            get
            {
                return this._Comment1;
            }
            set
            {
                this.OnComment1Changing(value);
                this._Comment1 = value;
                this.OnComment1Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment1;
        partial void OnComment1Changing(string value);
        partial void OnComment1Changed();
        /// <summary>
        /// There are no comments for Property RequirementID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> RequirementID
        {
            get
            {
                return this._RequirementID;
            }
            set
            {
                this.OnRequirementIDChanging(value);
                this._RequirementID = value;
                this.OnRequirementIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _RequirementID;
        partial void OnRequirementIDChanging(global::System.Nullable<long> value);
        partial void OnRequirementIDChanged();
    }
    /// <summary>
    /// There are no comments for QAManagementModel.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Project
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Project CreateProject(long ID)
        {
            Project project = new Project();
            project.ID = ID;
            return project;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnCompanyIDChanging(value);
                this._CompanyID = value;
                this.OnCompanyIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _CompanyID;
        partial void OnCompanyIDChanging(global::System.Nullable<long> value);
        partial void OnCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property TestingDepth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> TestingDepth
        {
            get
            {
                return this._TestingDepth;
            }
            set
            {
                this.OnTestingDepthChanging(value);
                this._TestingDepth = value;
                this.OnTestingDepthChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _TestingDepth;
        partial void OnTestingDepthChanging(global::System.Nullable<byte> value);
        partial void OnTestingDepthChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        /// <summary>
        /// There are no comments for Project1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project1
        {
            get
            {
                return this._Project1;
            }
            set
            {
                this._Project1 = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project1;
        /// <summary>
        /// There are no comments for Project2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project2
        {
            get
            {
                return this._Project2;
            }
            set
            {
                this._Project2 = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project2;
        /// <summary>
        /// There are no comments for ProjectUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ProjectUser> ProjectUsers
        {
            get
            {
                return this._ProjectUsers;
            }
            set
            {
                if ((value != null))
                {
                    this._ProjectUsers = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ProjectUser> _ProjectUsers = new global::System.Collections.ObjectModel.Collection<ProjectUser>();
        /// <summary>
        /// There are no comments for Requirements in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Requirement> Requirements
        {
            get
            {
                return this._Requirements;
            }
            set
            {
                if ((value != null))
                {
                    this._Requirements = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Requirement> _Requirements = new global::System.Collections.ObjectModel.Collection<Requirement>();
    }
    /// <summary>
    /// There are no comments for QAManagementModel.ProjectUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class ProjectUser
    {
        /// <summary>
        /// Create a new ProjectUser object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ProjectUser CreateProjectUser(long ID)
        {
            ProjectUser projectUser = new ProjectUser();
            projectUser.ID = ID;
            return projectUser;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this._UserID = value;
                this.OnUserIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _UserID;
        partial void OnUserIDChanging(global::System.Nullable<long> value);
        partial void OnUserIDChanged();
        /// <summary>
        /// There are no comments for Property ProjectID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ProjectID;
        partial void OnProjectIDChanging(global::System.Nullable<long> value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project
        {
            get
            {
                return this._Project;
            }
            set
            {
                this._Project = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
    }
    /// <summary>
    /// There are no comments for QAManagementModel.Requirement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Requirement
    {
        /// <summary>
        /// Create a new Requirement object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Requirement CreateRequirement(long ID)
        {
            Requirement requirement = new Requirement();
            requirement.ID = ID;
            return requirement;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property LongDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LongDescription
        {
            get
            {
                return this._LongDescription;
            }
            set
            {
                this.OnLongDescriptionChanging(value);
                this._LongDescription = value;
                this.OnLongDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LongDescription;
        partial void OnLongDescriptionChanging(string value);
        partial void OnLongDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property ProjectID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ProjectID
        {
            get
            {
                return this._ProjectID;
            }
            set
            {
                this.OnProjectIDChanging(value);
                this._ProjectID = value;
                this.OnProjectIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ProjectID;
        partial void OnProjectIDChanging(global::System.Nullable<long> value);
        partial void OnProjectIDChanged();
        /// <summary>
        /// There are no comments for Property SpecificationReference in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SpecificationReference
        {
            get
            {
                return this._SpecificationReference;
            }
            set
            {
                this.OnSpecificationReferenceChanging(value);
                this._SpecificationReference = value;
                this.OnSpecificationReferenceChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SpecificationReference;
        partial void OnSpecificationReferenceChanging(string value);
        partial void OnSpecificationReferenceChanged();
        /// <summary>
        /// There are no comments for Property PassingDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PassingDescription
        {
            get
            {
                return this._PassingDescription;
            }
            set
            {
                this.OnPassingDescriptionChanging(value);
                this._PassingDescription = value;
                this.OnPassingDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PassingDescription;
        partial void OnPassingDescriptionChanging(string value);
        partial void OnPassingDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Weighting in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> Weighting
        {
            get
            {
                return this._Weighting;
            }
            set
            {
                this.OnWeightingChanging(value);
                this._Weighting = value;
                this.OnWeightingChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _Weighting;
        partial void OnWeightingChanging(global::System.Nullable<long> value);
        partial void OnWeightingChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project
        {
            get
            {
                return this._Project;
            }
            set
            {
                this._Project = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project;
        /// <summary>
        /// There are no comments for TestResults in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<TestResult> TestResults
        {
            get
            {
                return this._TestResults;
            }
            set
            {
                if ((value != null))
                {
                    this._TestResults = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<TestResult> _TestResults = new global::System.Collections.ObjectModel.Collection<TestResult>();
    }
    /// <summary>
    /// There are no comments for QAManagementModel.TestResult in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class TestResult
    {
        /// <summary>
        /// Create a new TestResult object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TestResult CreateTestResult(long ID)
        {
            TestResult testResult = new TestResult();
            testResult.ID = ID;
            return testResult;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Results in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Results
        {
            get
            {
                return this._Results;
            }
            set
            {
                this.OnResultsChanging(value);
                this._Results = value;
                this.OnResultsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Results;
        partial void OnResultsChanging(string value);
        partial void OnResultsChanged();
        /// <summary>
        /// There are no comments for Property RequirementID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> RequirementID
        {
            get
            {
                return this._RequirementID;
            }
            set
            {
                this.OnRequirementIDChanging(value);
                this._RequirementID = value;
                this.OnRequirementIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _RequirementID;
        partial void OnRequirementIDChanging(global::System.Nullable<long> value);
        partial void OnRequirementIDChanged();
        /// <summary>
        /// There are no comments for Property Pass in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Pass
        {
            get
            {
                return this._Pass;
            }
            set
            {
                this.OnPassChanging(value);
                this._Pass = value;
                this.OnPassChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Pass;
        partial void OnPassChanging(global::System.Nullable<bool> value);
        partial void OnPassChanged();
        /// <summary>
        /// There are no comments for Requirement in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Requirement Requirement
        {
            get
            {
                return this._Requirement;
            }
            set
            {
                this._Requirement = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Requirement _Requirement;
    }
    /// <summary>
    /// There are no comments for QAManagementModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class User
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="companyID">Initial value of CompanyID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(long ID, long companyID)
        {
            User user = new User();
            user.ID = ID;
            user.CompanyID = companyID;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this._Username = value;
                this.OnUsernameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property CompanyID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long CompanyID
        {
            get
            {
                return this._CompanyID;
            }
            set
            {
                this.OnCompanyIDChanging(value);
                this._CompanyID = value;
                this.OnCompanyIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _CompanyID;
        partial void OnCompanyIDChanging(long value);
        partial void OnCompanyIDChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Address1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this.OnAddress1Changing(value);
                this._Address1 = value;
                this.OnAddress1Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address1;
        partial void OnAddress1Changing(string value);
        partial void OnAddress1Changed();
        /// <summary>
        /// There are no comments for Property Address2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this.OnAddress2Changing(value);
                this._Address2 = value;
                this.OnAddress2Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address2;
        partial void OnAddress2Changing(string value);
        partial void OnAddress2Changed();
        /// <summary>
        /// There are no comments for Property Address3 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address3
        {
            get
            {
                return this._Address3;
            }
            set
            {
                this.OnAddress3Changing(value);
                this._Address3 = value;
                this.OnAddress3Changed();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address3;
        partial void OnAddress3Changing(string value);
        partial void OnAddress3Changed();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property CellNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CellNumber
        {
            get
            {
                return this._CellNumber;
            }
            set
            {
                this.OnCellNumberChanging(value);
                this._CellNumber = value;
                this.OnCellNumberChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CellNumber;
        partial void OnCellNumberChanging(string value);
        partial void OnCellNumberChanged();
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Company
        {
            get
            {
                return this._Company;
            }
            set
            {
                this._Company = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Company;
        /// <summary>
        /// There are no comments for ProjectUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ProjectUser> ProjectUsers
        {
            get
            {
                return this._ProjectUsers;
            }
            set
            {
                if ((value != null))
                {
                    this._ProjectUsers = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ProjectUser> _ProjectUsers = new global::System.Collections.ObjectModel.Collection<ProjectUser>();
    }
}
