//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAManagement.AssessmentAgent.ProjectService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Project : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2 CompanyReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Project Project1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 Project1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Project Project2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 Project2ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.ProjectUser> ProjectUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Requirement> RequirementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> TestingDepthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2 CompanyReference {
            get {
                return this.CompanyReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyReferenceField, value) != true)) {
                    this.CompanyReferenceField = value;
                    this.RaisePropertyChanged("CompanyReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Project Project1 {
            get {
                return this.Project1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Project1Field, value) != true)) {
                    this.Project1Field = value;
                    this.RaisePropertyChanged("Project1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 Project1Reference {
            get {
                return this.Project1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Project1ReferenceField, value) != true)) {
                    this.Project1ReferenceField = value;
                    this.RaisePropertyChanged("Project1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Project Project2 {
            get {
                return this.Project2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Project2Field, value) != true)) {
                    this.Project2Field = value;
                    this.RaisePropertyChanged("Project2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 Project2Reference {
            get {
                return this.Project2ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Project2ReferenceField, value) != true)) {
                    this.Project2ReferenceField = value;
                    this.RaisePropertyChanged("Project2Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.ProjectUser> ProjectUsers {
            get {
                return this.ProjectUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectUsersField, value) != true)) {
                    this.ProjectUsersField = value;
                    this.RaisePropertyChanged("ProjectUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Requirement> Requirements {
            get {
                return this.RequirementsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementsField, value) != true)) {
                    this.RequirementsField = value;
                    this.RaisePropertyChanged("Requirements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TestingDepth {
            get {
                return this.TestingDepthField;
            }
            set {
                if ((this.TestingDepthField.Equals(value) != true)) {
                    this.TestingDepthField = value;
                    this.RaisePropertyChanged("TestingDepth");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Company))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.PaymentPoint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.ProjectUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Requirement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Step))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.TestResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Project))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Company))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.PaymentPoint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.ProjectUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Requirement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Step))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.TestResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Project))]
    public partial class EntityObject : QAManagement.AssessmentAgent.ProjectService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Company : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Project> ProjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.User> UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ValidatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPersonNumber {
            get {
                return this.ContactPersonNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonNumberField, value) != true)) {
                    this.ContactPersonNumberField = value;
                    this.RaisePropertyChanged("ContactPersonNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeEmail {
            get {
                return this.OfficeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeEmailField, value) != true)) {
                    this.OfficeEmailField = value;
                    this.RaisePropertyChanged("OfficeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePhoneNumber {
            get {
                return this.OfficePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficePhoneNumberField, value) != true)) {
                    this.OfficePhoneNumberField = value;
                    this.RaisePropertyChanged("OfficePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Project> Projects {
            get {
                return this.ProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectsField, value) != true)) {
                    this.ProjectsField = value;
                    this.RaisePropertyChanged("Projects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.User> Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Validated {
            get {
                return this.ValidatedField;
            }
            set {
                if ((this.ValidatedField.Equals(value) != true)) {
                    this.ValidatedField = value;
                    this.RaisePropertyChanged("Validated");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2 CompanyReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.PaymentPoint> PaymentPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PaypointThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.ProjectUser> ProjectUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Requirement> RequirementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNoField, value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber {
            get {
                return this.CellNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CellNumberField, value) != true)) {
                    this.CellNumberField = value;
                    this.RaisePropertyChanged("CellNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2 CompanyReference {
            get {
                return this.CompanyReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyReferenceField, value) != true)) {
                    this.CompanyReferenceField = value;
                    this.RaisePropertyChanged("CompanyReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.PaymentPoint> PaymentPoints {
            get {
                return this.PaymentPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentPointsField, value) != true)) {
                    this.PaymentPointsField = value;
                    this.RaisePropertyChanged("PaymentPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PaypointThreshold {
            get {
                return this.PaypointThresholdField;
            }
            set {
                if ((this.PaypointThresholdField.Equals(value) != true)) {
                    this.PaypointThresholdField = value;
                    this.RaisePropertyChanged("PaypointThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.ProjectUser> ProjectUsers {
            get {
                return this.ProjectUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectUsersField, value) != true)) {
                    this.ProjectUsersField = value;
                    this.RaisePropertyChanged("ProjectUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Requirement> Requirements {
            get {
                return this.RequirementsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementsField, value) != true)) {
                    this.RequirementsField = value;
                    this.RaisePropertyChanged("Requirements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentPoint", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PaymentPoint : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectUser", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProjectUser : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 ProjectReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 ProjectReference {
            get {
                return this.ProjectReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectReferenceField, value) != true)) {
                    this.ProjectReferenceField = value;
                    this.RaisePropertyChanged("ProjectReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Requirement", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Requirement : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> OwnedByUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassingDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 ProjectReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Requirement Requirement1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 Requirement1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Requirement Requirement2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 Requirement2ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecificationReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Step> StepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.TestResult> TestResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> WeightingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OwnedByUserID {
            get {
                return this.OwnedByUserIDField;
            }
            set {
                if ((this.OwnedByUserIDField.Equals(value) != true)) {
                    this.OwnedByUserIDField = value;
                    this.RaisePropertyChanged("OwnedByUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassingDescription {
            get {
                return this.PassingDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PassingDescriptionField, value) != true)) {
                    this.PassingDescriptionField = value;
                    this.RaisePropertyChanged("PassingDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2 ProjectReference {
            get {
                return this.ProjectReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectReferenceField, value) != true)) {
                    this.ProjectReferenceField = value;
                    this.RaisePropertyChanged("ProjectReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Requirement Requirement1 {
            get {
                return this.Requirement1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Requirement1Field, value) != true)) {
                    this.Requirement1Field = value;
                    this.RaisePropertyChanged("Requirement1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 Requirement1Reference {
            get {
                return this.Requirement1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Requirement1ReferenceField, value) != true)) {
                    this.Requirement1ReferenceField = value;
                    this.RaisePropertyChanged("Requirement1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Requirement Requirement2 {
            get {
                return this.Requirement2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Requirement2Field, value) != true)) {
                    this.Requirement2Field = value;
                    this.RaisePropertyChanged("Requirement2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 Requirement2Reference {
            get {
                return this.Requirement2ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.Requirement2ReferenceField, value) != true)) {
                    this.Requirement2ReferenceField = value;
                    this.RaisePropertyChanged("Requirement2Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecificationReference {
            get {
                return this.SpecificationReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationReferenceField, value) != true)) {
                    this.SpecificationReferenceField = value;
                    this.RaisePropertyChanged("SpecificationReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Step> Steps {
            get {
                return this.StepsField;
            }
            set {
                if ((object.ReferenceEquals(this.StepsField, value) != true)) {
                    this.StepsField = value;
                    this.RaisePropertyChanged("Steps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.TestResult> TestResults {
            get {
                return this.TestResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.TestResultsField, value) != true)) {
                    this.TestResultsField = value;
                    this.RaisePropertyChanged("TestResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2 UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UserReferenceField, value) != true)) {
                    this.UserReferenceField = value;
                    this.RaisePropertyChanged("UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Weighting {
            get {
                return this.WeightingField;
            }
            set {
                if ((this.WeightingField.Equals(value) != true)) {
                    this.WeightingField = value;
                    this.RaisePropertyChanged("Weighting");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Step", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Step : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Requirement RequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RequirementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 RequirementReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsTest {
            get {
                return this.IsTestField;
            }
            set {
                if ((this.IsTestField.Equals(value) != true)) {
                    this.IsTestField = value;
                    this.RaisePropertyChanged("IsTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Requirement Requirement {
            get {
                return this.RequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementField, value) != true)) {
                    this.RequirementField = value;
                    this.RaisePropertyChanged("Requirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RequirementID {
            get {
                return this.RequirementIDField;
            }
            set {
                if ((this.RequirementIDField.Equals(value) != true)) {
                    this.RequirementIDField = value;
                    this.RaisePropertyChanged("RequirementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 RequirementReference {
            get {
                return this.RequirementReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementReferenceField, value) != true)) {
                    this.RequirementReferenceField = value;
                    this.RaisePropertyChanged("RequirementReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestResult", Namespace="http://schemas.datacontract.org/2004/07/QAManagement.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TestResult : QAManagement.AssessmentAgent.ProjectService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.Requirement RequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RequirementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 RequirementReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Pass {
            get {
                return this.PassField;
            }
            set {
                if ((this.PassField.Equals(value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.Requirement Requirement {
            get {
                return this.RequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementField, value) != true)) {
                    this.RequirementField = value;
                    this.RaisePropertyChanged("Requirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RequirementID {
            get {
                return this.RequirementIDField;
            }
            set {
                if ((this.RequirementIDField.Equals(value) != true)) {
                    this.RequirementIDField = value;
                    this.RaisePropertyChanged("RequirementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2 RequirementReference {
            get {
                return this.RequirementReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RequirementReferenceField, value) != true)) {
                    this.RequirementReferenceField = value;
                    this.RaisePropertyChanged("RequirementReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCompany0gTJnmO2", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCompany0gTJnmO2 : QAManagement.AssessmentAgent.ProjectService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProject0gTJnmO2", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfProject0gTJnmO2 : QAManagement.AssessmentAgent.ProjectService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Project>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Company))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.User>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.PaymentPoint>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.PaymentPoint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.ProjectUser>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.ProjectUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Requirement>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Requirement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Step>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.Step))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.TestResult>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.TestResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2))]
    public partial class EntityReference : QAManagement.AssessmentAgent.ProjectService.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QAManagement.AssessmentAgent.ProjectService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QAManagement.AssessmentAgent.ProjectService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfUser0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfProject0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfRequirement0gTJnmO2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(QAManagement.AssessmentAgent.ProjectService.EntityReferenceOfCompany0gTJnmO2))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfUser0gTJnmO2", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfUser0gTJnmO2 : QAManagement.AssessmentAgent.ProjectService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfRequirement0gTJnmO2", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfRequirement0gTJnmO2 : QAManagement.AssessmentAgent.ProjectService.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectService.IProjects")]
    public interface IProjects {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjects/GetProjectsByCompany", ReplyAction="http://tempuri.org/IProjects/GetProjectsByCompanyResponse")]
        QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse GetProjectsByCompany(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProjects/GetProjectsByCompany", ReplyAction="http://tempuri.org/IProjects/GetProjectsByCompanyResponse")]
        System.IAsyncResult BeginGetProjectsByCompany(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request, System.AsyncCallback callback, object asyncState);
        
        QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse EndGetProjectsByCompany(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectsByCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProjectsByCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CompanyID;
        
        public GetProjectsByCompanyRequest() {
        }
        
        public GetProjectsByCompanyRequest(int CompanyID) {
            this.CompanyID = CompanyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProjectsByCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProjectsByCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Project> GetProjectsByCompanyResult;
        
        public GetProjectsByCompanyResponse() {
        }
        
        public GetProjectsByCompanyResponse(System.Collections.ObjectModel.Collection<QAManagement.AssessmentAgent.ProjectService.Project> GetProjectsByCompanyResult) {
            this.GetProjectsByCompanyResult = GetProjectsByCompanyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectsChannel : QAManagement.AssessmentAgent.ProjectService.IProjects, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProjectsByCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProjectsByCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectsClient : System.ServiceModel.ClientBase<QAManagement.AssessmentAgent.ProjectService.IProjects>, QAManagement.AssessmentAgent.ProjectService.IProjects {
        
        private BeginOperationDelegate onBeginGetProjectsByCompanyDelegate;
        
        private EndOperationDelegate onEndGetProjectsByCompanyDelegate;
        
        private System.Threading.SendOrPostCallback onGetProjectsByCompanyCompletedDelegate;
        
        public ProjectsClient() {
        }
        
        public ProjectsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetProjectsByCompanyCompletedEventArgs> GetProjectsByCompanyCompleted;
        
        public QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse GetProjectsByCompany(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request) {
            return base.Channel.GetProjectsByCompany(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetProjectsByCompany(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProjectsByCompany(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse EndGetProjectsByCompany(System.IAsyncResult result) {
            return base.Channel.EndGetProjectsByCompany(result);
        }
        
        private System.IAsyncResult OnBeginGetProjectsByCompany(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request = ((QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest)(inValues[0]));
            return this.BeginGetProjectsByCompany(request, callback, asyncState);
        }
        
        private object[] OnEndGetProjectsByCompany(System.IAsyncResult result) {
            QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyResponse retVal = this.EndGetProjectsByCompany(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProjectsByCompanyCompleted(object state) {
            if ((this.GetProjectsByCompanyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProjectsByCompanyCompleted(this, new GetProjectsByCompanyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProjectsByCompanyAsync(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request) {
            this.GetProjectsByCompanyAsync(request, null);
        }
        
        public void GetProjectsByCompanyAsync(QAManagement.AssessmentAgent.ProjectService.GetProjectsByCompanyRequest request, object userState) {
            if ((this.onBeginGetProjectsByCompanyDelegate == null)) {
                this.onBeginGetProjectsByCompanyDelegate = new BeginOperationDelegate(this.OnBeginGetProjectsByCompany);
            }
            if ((this.onEndGetProjectsByCompanyDelegate == null)) {
                this.onEndGetProjectsByCompanyDelegate = new EndOperationDelegate(this.OnEndGetProjectsByCompany);
            }
            if ((this.onGetProjectsByCompanyCompletedDelegate == null)) {
                this.onGetProjectsByCompanyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProjectsByCompanyCompleted);
            }
            base.InvokeAsync(this.onBeginGetProjectsByCompanyDelegate, new object[] {
                        request}, this.onEndGetProjectsByCompanyDelegate, this.onGetProjectsByCompanyCompletedDelegate, userState);
        }
    }
}
